/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControlIndeceCoronariano;
import model.ModelIndiceCoronariano;

/**
 *
 * @author misae
 */
public class IndiceCoronariano extends javax.swing.JFrame {

    /**
     * Creates new form IndiceCoronariano
     */
    ControlIndeceCoronariano conInd = new ControlIndeceCoronariano();
    ModelIndiceCoronariano modInt = new ModelIndiceCoronariano();
    public IndiceCoronariano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxIdade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxHereditariedade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPeso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFumo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxExercicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxColesterol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxpresao = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RISKO - TESTE DE ÍNDICE CORONARIANO ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxIdade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "10 - 20 anos", "21 - 30 anos", "31 - 40 anos", "41 - 50 anos", "51 - 60 anos", "61 - 70 anos" }));

        jLabel3.setText("Idade:");

        jLabel2.setText("Hereditariedade:");

        jComboBoxHereditariedade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Nenhuma história reconhecida", "1 parente com + de 60 anos com doença cardiovascular", "2 parentes com + de 60 anos com doença cardiovascular", "1 parente com - de 60 anos com doença cardiovascular", "2 parentes com - de 60 anos com doença cardiovascular", "3 parente com - de 60 anos com doença cardiovascular" }));

        jLabel4.setText("Peso:");

        jComboBoxPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "+ de 2,3kg abaixo do peso padrão", "-2,3kg a +2,3kg do peso padrão", "Excesso de peso padrão de 2,7kg-9kg", "Excesso de peso padrão de 9,1kg-15,8kg", "Excesso de peso padrão de 16,2 kg-22,6 kg", "Excesso de peso padrão de 23,0 kg-29,5 kg" }));

        jLabel5.setText("Fumo:");

        jComboBoxFumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Não Fumante", "Charuto e/ou cachimbo", "10 cigarros ou menos por dia", "20 cigarros por dia", "30 cigarros por dia", "40 cigarros ou mais por dia" }));

        jLabel6.setText("Exercício:");

        jComboBoxExercicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Esforço Ocupacional e recreacional intenso", "Esforço Ocupacional e recreacional moderado", "Trabalho sedentário e esforço recreacional intenso ", "Trabalho sedentário e esforço recreacional moderado", "Trabalho sedentário e esforço recreacional leve", "Ausência completa de qualquer exercício" }));

        jLabel7.setText("Colesterol ou % de gordura na dieta:");

        jComboBoxColesterol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Colesterol abaixo de 180mg% / Ausência de gorduras animais ou sólidas na dieta", "Colesterol de 181-205 mg% / 10% de gordura animal ou sólida na dieta", "Colesterol de 203-206 mg% / 20% de gordura animal ou sólida na dieta", "Colesterol de 231-255 mg% / 30% de gordura animal ou sólida na dieta", "Colesterol de 256-280 mg% / 40% de gordura animal ou sólida na dieta", "Colesterol de 281-330 mg% / 50% de gordura animal ou sólida na dieta" }));

        jLabel8.setText("Pressão arterial:");

        jComboBoxpresao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Limite superior de 100", "Limite superior de 120", "Limite superior de 140", "Limite superior de 160", "Limite superior de 180", "Limite superior de 200 ou mais" }));

        jLabel9.setText("Sexo:");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Mulher com menos de 40", "Mulher com 40-50", "Mulher com mais de 50", "Homem", "Homem atarracado", "Homem careca e atarracado" }));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxHereditariedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxFumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxpresao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxHereditariedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxpresao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int idade = jComboBoxIdade.getSelectedIndex();
        int her =   jComboBoxHereditariedade.getSelectedIndex();
        int cole = jComboBoxColesterol.getSelectedIndex();
        int Exercicio = jComboBoxExercicio.getSelectedIndex();
        int Fumo = jComboBoxFumo.getSelectedIndex();
        int Peso = jComboBoxPeso.getSelectedIndex();
        int Sexo = jComboBoxSexo.getSelectedIndex();
        int Presaoart = jComboBoxpresao.getSelectedIndex(); 
        int somaIdade = 0;
        int somaHer = 0;
        int somaCole = 0;
        int somaExer = 0;
        int somaFumo = 0;
        int somaPeso = 0;
        int somaSexo = 0;
        int somaPres = 0;
        int somaTotal = 0;
        
switch (idade) {
   case 1:
           somaIdade = 1;
           break;
   case 2:
           somaIdade = 2;
           break;
   case 3:
           somaIdade = 3;
           break;
   case 4:
           somaIdade = 4;
           break;           
   case 5:
           somaIdade = 6;
           break;
   case 6:
           somaIdade = 8;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (her) {
   case 1:
           somaHer = 1;
           break;
   case 2:
          somaHer = 2;
           break;
   case 3:
           somaHer = 3;
           break;
   case 4:
           somaHer = 4;
           break;           
   case 5:
           somaHer = 6;
           break;
   case 6:
           somaHer = 8;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (cole) {
   case 1:
           somaCole = 1;
           break;
   case 2:
           somaCole = 2;
           break;
   case 3:
           somaCole = 3;
           break;
   case 4:
           somaCole = 4;
           break;           
   case 5:
           somaCole = 5;
           break;
   case 6:
           somaCole = 7;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (Exercicio) {
   case 1:
           somaExer = 1;
           break;
   case 2:
           somaExer = 2;
           break;
   case 3:
           somaExer = 3;
           break;
   case 4:
           somaExer = 5;
           break;           
   case 5:
           somaExer = 6;
           break;
   case 6:
           somaExer = 8;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (Fumo) {
   case 1:
           somaFumo = 0;
           break;
   case 2:
           somaFumo = 1;
           break;
   case 3:
           somaFumo = 2;
           break;
   case 4:
           somaFumo = 4;
           break;           
   case 5:
           somaFumo = 6;
           break;
   case 6:
           somaFumo = 10;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (Peso) {
   case 1:
           somaPeso = 0;
           break;
   case 2:
           somaPeso = 1;
           break;
   case 3:
           somaPeso = 2;
           break;
   case 4:
           somaPeso = 3;
           break;           
   case 5:
           somaPeso = 5;
           break;
   case 6:
           somaPeso = 7;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (Sexo) {
   case 1:
           somaSexo = 1;
           break;
   case 2:
           somaSexo = 2;
           break;
   case 3:
           somaSexo = 3;
           break;
   case 4:
           somaSexo = 5;
           break;           
   case 5:
           somaSexo = 6;
           break;
   case 6:
           somaSexo = 7;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}

switch (Presaoart) {
   case 1:
           somaPres = 1;
           break;
   case 2:
           somaPres = 2;
           break;
   case 3:
           somaPres = 3;
           break;
   case 4:
           somaPres = 4;
           break;           
   case 5:
           somaPres = 6;
           break;
   case 6:
           somaPres = 8;
           break;            
  default:
           System.out.println ("Selecione uma opção");
}
        somaTotal = somaIdade + somaHer + somaCole + somaExer + somaFumo + somaPeso + somaSexo + somaPres + somaTotal;
        
        System.out.println("Dados Inseridos na variavel: " +somaIdade);
        modInt.setIdade(somaIdade);
        
        System.out.println("Dados Inseridos no botão: " +modInt.getIdade());
        modInt.setHereditariedade(somaHer);
        modInt.setColesterol(jComboBoxColesterol.getSelectedIndex());
        modInt.setExercicio(jComboBoxExercicio.getSelectedIndex());
        modInt.setFumo(jComboBoxFumo.getSelectedIndex());
        modInt.setPeso(jComboBoxPeso.getSelectedIndex());
        modInt.setSexo(jComboBoxSexo.getSelectedIndex());
        modInt.setPresaoart(jComboBoxpresao.getSelectedIndex()); 
        modInt.setSoma(somaTotal);
        conInd.Salvar(modInt);
       
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndiceCoronariano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndiceCoronariano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndiceCoronariano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndiceCoronariano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndiceCoronariano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxColesterol;
    private javax.swing.JComboBox<String> jComboBoxExercicio;
    private javax.swing.JComboBox<String> jComboBoxFumo;
    private javax.swing.JComboBox<String> jComboBoxHereditariedade;
    private javax.swing.JComboBox<String> jComboBoxIdade;
    private javax.swing.JComboBox<String> jComboBoxPeso;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxpresao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
