/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.ConexaoBD;
import model.ModelAvaliacaoAntropometrica;
import control.ControlAvaliaçãoAntropometrica;
import control.PreencherTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelTabela;
import control.PreencherTabela;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.text.TableView;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author misae
 */
public class ResultadoAntropometrico extends javax.swing.JFrame {
    ModelAvaliacaoAntropometrica modelo = new ModelAvaliacaoAntropometrica();
    ControlAvaliaçãoAntropometrica controle = new ControlAvaliaçãoAntropometrica();
    ConexaoBD conectar = new ConexaoBD();
    
    /**
     * Creates new form ResultadoAntropometrico
     */
    public ResultadoAntropometrico() {
        initComponents();
        preencherTB("SELECT * FROM cadastrodepacientes INNER JOIN avaliacaoantropometrica ON cadastrodepacientes.id_Paci = avaliacaoantropometrica.idPac_Avali ORDER BY nome_Paci"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Guia = new javax.swing.JTabbedPane();
        result_Antropometrico = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Antropometrico = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CPF:");

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiltroActionPerformed(evt);
            }
        });
        jTextFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFiltro)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tb_Antropometrico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_Antropometrico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_AntropometricoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Antropometrico);

        javax.swing.GroupLayout result_AntropometricoLayout = new javax.swing.GroupLayout(result_Antropometrico);
        result_Antropometrico.setLayout(result_AntropometricoLayout);
        result_AntropometricoLayout.setHorizontalGroup(
            result_AntropometricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_AntropometricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(result_AntropometricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap())
        );
        result_AntropometricoLayout.setVerticalGroup(
            result_AntropometricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_AntropometricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Guia.addTab("Resultado Antropométrico", result_Antropometrico);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        Guia.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        Guia.addTab("tab3", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        Guia.addTab("tab4", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Guia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Guia)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void tb_AntropometricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_AntropometricoMouseClicked
        // TODO add your handling code here:
       
        int id_Ava = Integer.parseInt(""+tb_Antropometrico.getValueAt(tb_Antropometrico.getSelectedRow(),0));
        
        controle.imprimeRelatorio(id_Ava);

        
    }//GEN-LAST:event_tb_AntropometricoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        preencherTB("SELECT * FROM cadastrodepacientes INNER JOIN avaliacaoantropometrica ON cadastrodepacientes.id_Paci = avaliacaoantropometrica.idPac_Avali ORDER BY nome_Paci"); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiltroKeyTyped
        // TODO add your handling code here:
        //Editando aqui para filtro table

        
    }//GEN-LAST:event_jTextFiltroKeyTyped

    private void jTextFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFiltroActionPerformed

    public void preencherTB (String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []
        {
            "ID",
            "Nome",
            "Sobrenome",
            "CPF",
            "Data da Avaliação",
        };
            ConexaoBD.Conectar();
            conectar.executaSQL(sql);
             // campos que vão compor a tabela
        try
        {
            conectar.rs.first();
                        
            do
            {
                dados.add(new Object []
                {
                     conectar.rs.getInt("id_Avali"),
                     conectar.rs.getString("nome_Paci"),
                     conectar.rs.getString("sobrenome_Paci"),
                     conectar.rs.getString("cpf_Paci"),
                     conectar.rs.getString("data_Avali"),
                });
            }while (conectar.rs.next());
        }
        catch (SQLException ex)
            {
              JOptionPane.showMessageDialog (rootPane, "Não foi possivel atualizar a tabela!" +ex);    
            }
           ModelTabela modeloTabela = new ModelTabela(dados, colunas) {};
           
        
        // dados das colunas 
            tb_Antropometrico.setModel(modeloTabela);
            tb_Antropometrico.getColumnModel().getColumn(0).setPreferredWidth(50); // id
            tb_Antropometrico.getColumnModel().getColumn(0).setResizable(false);
            tb_Antropometrico.getColumnModel().getColumn(1).setPreferredWidth(110); // nomePac
            tb_Antropometrico.getColumnModel().getColumn(1).setResizable(false);
            tb_Antropometrico.getColumnModel().getColumn(2).setPreferredWidth(110); // sobrenomePac
            tb_Antropometrico.getColumnModel().getColumn(2).setResizable(false);
            tb_Antropometrico.getColumnModel().getColumn(3).setPreferredWidth(100); // cpf
            tb_Antropometrico.getColumnModel().getColumn(3).setResizable(false);
            tb_Antropometrico.getColumnModel().getColumn(4).setPreferredWidth(100); // data_Ava
            tb_Antropometrico.getColumnModel().getColumn(4).setResizable(false);
            tb_Antropometrico.getTableHeader().setReorderingAllowed(false);
            tb_Antropometrico.setAutoResizeMode(tb_Antropometrico.AUTO_RESIZE_OFF);
            tb_Antropometrico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
            
            conectar.Desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoAntropometrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoAntropometrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoAntropometrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoAntropometrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoAntropometrico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Guia;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFiltro;
    private javax.swing.JPanel result_Antropometrico;
    private javax.swing.JTable tb_Antropometrico;
    // End of variables declaration//GEN-END:variables
}
